---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://defworld.com

posts:
  permalink: /poems/:year/:month/:day/:filename.html
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
